### ISSUE TITLE
How do I change default RC dir to /etc?

### ISSUE THREAD

**Issue by bakoontz2** [sdaoden/s-mailx#1]
I'm building s-nail using a package manager.  Right now, my build steps look like this:

```
  - runs: |
      set -x
      make config
      make build
      make install
      cp /home/build/.obj/s-nail /bin/s-nail
      mkdir "${{targets.destdir}}/bin"
      cp /home/build/.obj/s-nail "${{targets.destdir}}/bin/s-nail"
      cp /home/build/.obj/s-nail-dotlock /bin/s-nail-dotlock
      cp /home/build/.obj/s-nail-dotlock "${{targets.destdir}}/bin/s-nail-dotlock"
      cp /home/build/.obj/urc.rc "${{targets.destdir}}/etc/s-nail.rc"
```
I would like to have urc.rc live in /etc/ rather than /usr/local/etc.  How do I modify the make commands so that the s-nail executable recognizes /etc/s-nail.rc?

**Comment by sdaoden** [comment]
hello. eh, normally one should post to the mailing-list, it seems github no longer allows blocking interactions etc, hm.  I am not very used to github, etc etc.
But thanks for your question, the current NetBSD maintainer had the same request, and i have in the TODO file
<code>
  The list of doing things proper is:
  1. s-nail points to ${PREFIX}/etc/s-nail.rc for default
  2. pkgsrc install s-nail.rc to ${PREFIX}/share/examples/s-nail/
  3. pkgsrc copies s-nail.rc from examples to etc if it's missing
     from etc.

  You can probably see the issue given that list -- s-nail doesn't want
  to install the default config in a different location than it expects
  it to be. Therefore, the patch was born. I hope that makes sense.
  ---
  Possibly the best would thus be to add another packager option,
  like VAL_INSTALL_SYSCONFDIR, or similar.  Then the MUA would
  continue to look for VAL_SYSCONFDIR/VAL_SYSCONFRC, but the
  installation script would instead install only to
  VAL_INSTALL_SYSCONFDIR/VAL_SYSCONFRC.
  Does this sound sane enough?  Will do!
</code>
I also wonder why you run "make install" when you then copy files around as such?
Or could it be your particular issue can be overcome by specifying any/both of VAL_SYSCONFDIR and VAL_SYSCONFRC?  This is documented in the file make.rc in the top directory of the release ball / repository?

**Comment by bakoontz2** [comment]
> hello. eh, normally one should post to the mailing-list, it seems github no longer allows blocking interactions etc, hm. I am not very used to github, etc etc.

You're right, I just spend all my time on github and was being lazy.  Will take up the issue on the mailing list!

For some reason, the package builder (melange) refuses to do the right thing with the executables when running "make install." I suspect it has something to do with ${PREFIX} not being set correctly.  I will take a look at that as well as the VAL_* env vars.

Thanks for the assist!
